account/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    # path('login/', user_login, name='login'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    # path('accounts/logout', auth_views.LogoutView.as_view(), name='logout'),
    path('logout/', views.logout_view, name='logout'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_change/',
         auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('account:password_change_done')),
         name='password_change'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(success_url=reverse_lazy('account:password_reset_done')),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('account:password_reset_complete')),
         name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path("profile/", views.profile, name="profile"),
    path('profile/edit',views.edit_account,name="edit_account"),
    path('profile/<int:pk>/comments',views.profile_comments,name="profile_comments"),
    path('auther/<str:author>',views.author_detail, name="auther_detail"),

]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path('posts/', views.post_list, name="post_list"),
    path('posts/<str:category>', views.post_list, name="post_list_category"),
    path('posts/detail/<pk>', views.post_item, name="post_item"),
    path('posts/<pk>/comment', views.post_comment, name="post_comment"),
    path("ticket/", views.ticket, name="ticket"),
    path("posts/new_post/create", views.create_post, name="create_post"),
    path("posts/new_post/create/<pk>", views.edit_post, name="edit_post"),
    path("posts/delete_image/<pk>", views.delete_image, name="delete_image"),
    path("posts/delete_post/<pk>", views.delete_post, name='delete_post'),
    path("search/", views.post_search, name="post_search"),
]

djangoFirstProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from djangoFirstProject import settings
from blog.views import index_page

urlpatterns = [
    path("", index_page, name="home"),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('account/', include('account.urls', namespace='account')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/forms.py
from django import forms
from .models import Comment, Post


class TicketForm(forms.Form):
    SUBJECT_CHOICES = (
        ("پیشنهادات", "پیشنهاد"),
        ("انتقادات", "انتقاد"),
        ("گزارشات", "گزارش"),
    )
    # label
    name = forms.CharField(max_length=255, required=True, widget=forms.TextInput(attrs={"class": "name_ticket",
                                                                                        "placeholder": "نام"}))
    email = forms.EmailField()
    phone = forms.CharField(max_length=12, required=True)
    subject = forms.ChoiceField(choices=SUBJECT_CHOICES)
    message = forms.CharField(widget=forms.Textarea)

    def clean_phone(self):
        phone = self.cleaned_data["phone"]
        if not phone.isnumeric():
            raise forms.ValidationError("شماره تلفن عددی نیست")
        else:
            return phone


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'body']
        widgets = {'body': forms.Textarea(attrs={"class": "comment_body"})}

    def clean_name(self):
        name = self.cleaned_data['name']
        if len(name) < 3:
            raise forms.ValidationError("اسم وارد شده باید بیشتر از ۳ کارکتر باشد")
        else:
            return name


class PostForm(forms.ModelForm):
    image_1 = forms.ImageField(label="تصویر اول", required=False)
    image_2 = forms.ImageField(label="تصویر دوم", required=False)

    class Meta:
        model = Post
        fields = ['title', 'description', 'reading_time','category']

        def clean_title(self):
            title = self.cleaned_data['title']
            if len(title) < 1:
                raise forms.ValidationError("باید موضوع بیشتر از ۱ کارکتر باشه ")
            elif len(title) > 250:
                raise forms.ValidationError("باید موضوع کمتر از ۲۵۰ کارکتر باشه")
            else:
                return title

        def clean_description(self):
            description = self.cleaned_data['description']
            if len(description) < 5:
                raise forms.ValidationError("باید موضوع بیشتر از ۵ کارکتر باشه ")
            else:
                return description

        def clean_reading_time(self):
            reading_time = self.cleaned_data['reading_time']
            if reading_time <= 0:
                raise forms.ValidationError("باید زمان خواندن بیشتر از ۰ باشد ")
            else:
                return reading_time


class SearchForm(forms.Form):
    query = forms.CharField()


class LoginForm(forms.Form):
    username = forms.CharField(max_length=250, label='نام کاربری:')
    password = forms.CharField(max_length=250, label='کلمه عبور:', widget=forms.PasswordInput)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from .models import Post, Ticket, Image
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView
from . import forms
from django.views.decorators.http import require_POST
from django.db.models import Avg, Max, Min
from django.db.models import Q
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity, SearchHeadline
from django.contrib.auth.decorators import login_required
import random


# Create your views here.

def index_page(request):
    aggregate_post = Post.published.aggregate(Avg("reading_time"), Max("reading_time"), Min("reading_time"))
    random_post = random.choice(Post.published.all())
    context = {
        'max_time': aggregate_post['reading_time__max'],
        'min_time': aggregate_post['reading_time__min'],
        'avg_time': aggregate_post['reading_time__avg'],
        'random_post': random_post
    }
    return render(request, 'index.html', context)


# func base view
def post_list(request, category=None):
    if category is not None:
        posts = Post.published.filter(category=category)
    else:
        posts = Post.published.all()
    categories = [i[0] for i in Post.CATEGORY_CHOICES]
    paginator = Paginator(posts, 2)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    # for example, we have 4 object , user enter 5 and Paginator rise EmptyPage
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)
    context = {
        "list_of_post": posts,
        'category': category,
        'categories': categories
    }
    return render(request, "blog/post_list.html", context)


# class base view
# class PostList(ListView):
#     queryset = Post.published.all()
#     # default is object_list
#     context_object_name = "list_of_post"
#     paginate_by = 2
#     template_name = "blog/post_list.html"


def post_item(request, pk):
    post = get_object_or_404(Post, id=pk, status=Post.Status.PUBLISH)
    form = forms.CommentForm()
    comments = post.comments.filter(active=True)
    context = {
        "post": post,
        'form': form,
        'comments': comments,
    }
    return render(request, "blog/post_detail.html", context)


# class PostItemDetail(DetailView):
#     template_name = "blog/post_detail.html"
#     model = Post

@login_required
@require_POST
def post_comment(request, pk):
    post = get_object_or_404(Post, id=pk, status=Post.Status.PUBLISH)
    comment = None
    form = forms.CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    context = {
        'post': post,
        'form': form,
        'comment': comment
    }
    return render(request, 'forms/comment.html', context)


def ticket(request):
    if request.method == "POST":
        form = forms.TicketForm(request.POST)
        if form.is_valid():
            ticket_obj = Ticket.objects.create()
            cd = form.cleaned_data
            ticket_obj.name = cd['name']
            ticket_obj.email = cd['email']
            ticket_obj.phone = cd['phone']
            ticket_obj.subject = cd['subject']
            ticket_obj.message = cd['message']
            ticket_obj.save()
            return redirect("blog:home")
    else:
        form = forms.TicketForm()
    return render(request, "forms/ticket.html", {'form': form})


@login_required
def create_post(request):
    if request.method == 'POST':
        form = forms.PostForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            post_form = form.save(commit=False)
            post_form.auther = request.user
            post_form.save()

            # method 2  for autofill slug field
            # post_form.slug = f"{user_id}-{form.cleaned_data['title']}"

            Image.objects.create(image_file=form.cleaned_data['image_1'], description=form.cleaned_data['description'],
                                 title=form.cleaned_data['title'], post=post_form)
            Image.objects.create(image_file=form.cleaned_data['image_2'], description=form.cleaned_data['description'],
                                 title=form.cleaned_data['title'], post=post_form)
            return redirect("blog:profile")

    else:
        form = forms.PostForm()
    context = {
        "form": form
    }

    return render(request, "forms/post.html", context)


def delete_post(request, pk):
    post = get_object_or_404(Post, id=pk)

    if request.method == "POST":
        post.delete()
        return redirect("blog:profile")
    context = {
        'post': post
    }
    return render(request, 'forms/delete-post.html', context)


def edit_post(request, pk):
    post = get_object_or_404(Post, id=pk)
    if request.method == "POST":
        form = forms.PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            if form.cleaned_data['image_1']:
                Image.objects.create(title=form.cleaned_data['title'], description=form.cleaned_data['description'],
                                     image_file=form.cleaned_data['image_1'], post=post)
                request.FILES.pop('image_1')
            if form.cleaned_data['image_2']:
                Image.objects.create(title=form.cleaned_data['title'], description=form.cleaned_data['description'],
                                     image_file=form.cleaned_data['image_2'], post=post)
                request.FILES.pop('image_2')

            # for edit Images
            for key, file in request.FILES.items():
                image_id = key.split('_')[1]
                if file:
                    image = Image.objects.get(id=image_id)
                    image.image_file = file
                    image.save()
        return redirect('blog:profile')
    else:
        form = forms.PostForm(instance=post)
    context = {
        'post': post,
        'form': form
    }
    return render(request, "forms/post.html", context)


def delete_image(request, pk):
    image = get_object_or_404(Image, id=pk)
    post_id = image.post.id
    image.delete()
    return redirect('blog:edit_post', pk=post_id)


def post_search(request):
    query = None
    results = []
    if 'query' in request.GET:
        form = forms.SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            # search with search query and search vector and search rank
            # search_query = SearchQuery(query)
            # search_vector = SearchVector('title', weight="A") + SearchVector('description', weight="B")
            # rank = SearchRank(search_vector, search_query, weights=[0.1, 0.3, 0.6, 0.9])
            # results = Post.published.annotate(search=search_vector, rank=rank) \
            #     .filter(rank__gte=0.4).order_by('-rank')

            # search with search trigram similarity
            result1 = Post.published.annotate(
                similar=TrigramSimilarity('title', query)).filter(similar__gt=0.1)

            result2 = Post.published.annotate(
                similar=TrigramSimilarity('description', query)).filter(similar__gt=0.1)

            result3 = Post.published.annotate(
                similar=TrigramSimilarity('images__description', query)).filter(similar__gt=0.05)
            results = (result1 | result2 | result3).order_by('-similar').annotate(
                headline=SearchHeadline("description", query))

    context = {
        'query': query,
        'results': results
    }
    return render(request, 'blog/search.html', context)

blog/templates/blog/index.html
{% extends 'parent/base.html' %}
{% load blog_tags %}
{% block title %}
    Index
{% endblock %}
{% block content %}
    <h2>آمار</h2>
    <p> تعداد پست ها : {% total_posts %} </p>
    <p> تعداد کامنت ها : {% all_comment %} </p>
    <p> تاریخ اخرین پست : {% last_published %} </p>
    <p> بیشترین زمان مطالعه هر پست : {{ max_time }} </p>
    <p> کمترین زمان مطالعه هر پست : {{ min_time }} </p>
    <p> میانگین زمان مطالعه هر پست : {{ avg_time }} </p>
    {% latest_post 3 %}

    <h2>بیشترین کامنت برای هر پست </h2>
    {% most_comments 3 as mos_com %}
    {% for post in mos_com %}
        <p><a href="{{ post.get_absolute_url }}">{{ post.title }}</a> with {{ post.comment_count }} comment</p>
    {% endfor %}

    <br><br>

    <a href="{% url "blog:create_post" %}">create post</a>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'parent/base.html' %}
{% load jformat %}
{% load blog_tags %}
{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    {% with post.images.all as post_images %}
        <h1 class="post-detail">{{ post.title }}</h1>

        {% images post_images 0 2 %}

        <p class="author"> نویسنده : <a href="{% url 'account:auther_detail' post.auther %}">{{ post.auther }}</a></p>
        <span class="pub-date">{{ post.publish|jformat:"%Y/%m/%d-%H:%M" }}</span>
        <div class="des">
            <p class="des-p">{{ post.description | markdown |censorship }}</p>

            {% images post_images 2 4 %}

        </div>

        {% images post_images 4 5 %}

    {% endwith %}
    <hr>

    {% with comments.count as comment_count %}
        <p>{{ comment_count }} comment{{ comment_count|pluralize }}</p>
    {% endwith %}

    {% post_comments post %}

    {% include 'forms/comment.html' %}

{% endblock %}

blog/templates/blog/post_list.html
{% extends 'parent/base.html' %}
{% block title %}
    Post List
{% endblock %}

{% block content %}
    {% if category %}
        <h1 class="post-list">{{ category }}</h1>
    {% else %}
        <h1 class="post-list">لیست پست ها</h1>
    {% endif %}
    <ul>
        <h3>دسته بندی</h3>
        {% for category in categories %}
            <li>
                <p><a href="{% url 'blog:post_list_category' category %}">{{ category }}</a></p>
            </li>
        {% endfor %}

    </ul>
    <ol style="--length: {{ list_of_post|length }}" role="list">
        {% for post in list_of_post %}
            <li style="--i: {{ forloop.counter }}">
                <h3 class="post-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h3>
                <h5>
                    نویسنده : <a href="{% url 'account:auther_detail' post.auther %}">{{ post.auther }}</a>
                </h5>
                <p class="descr"> {{ post.description | truncatewords:4 }}</p>
                {% if post.images.first.image_file %}
                    <img src="{{ post.images.first.image_file.url }}" alt="{{ post.images.first.title }}">
                {% endif %}
            </li>

        {% endfor %}
    </ol>

    {% include "partials/pagination.html" with page=list_of_post %}
{% endblock %}

blog/templates/blog/search.html
{% extends 'parent/base.html' %}
{% load blog_tags %}
{% block title %}
    search post
{% endblock %}

{% block content %}
    {% if query %}
        {% with results.count as result_count %}
            <p style="margin: 0 auto;width: max-content">search {{ query }} with {{ result_count }}
                result{{ result_count|pluralize }} </p>
        {% endwith %}
        <br><br>
        {% for post in results %}
            <a href="{{ post.get_absolute_url }}"> {{ post.title }}</a>
            <p>{{ post.headline|censorship }}</p>
        {% empty %}
            <p style="margin: 0 auto;width: max-content">!هیچ نتیحه ای پیدا نشد</p>
        {% endfor %}
    {% endif %}

{% endblock %}